/**
 * Name: Ratan J Naik
 * Course: CS-665 Software Designs & Patterns
 * Date: 03/05/2024
 * File Name: ContextEmail.java
 * Description: This class serves as the context in the Strategy pattern, allowing for dynamic
 * changes in the email generation strategy based on the type of customer. It utilizes the
 * EmailStrategy interface to delegate the generation of email messages.
 */

package edu.bu.met.cs665;

import edu.bu.met.cs665.interfaces.EmailStrategy;

/**
 * The ContextEmail class acts as the context for different email generation strategies. It holds
 * a reference to an EmailStrategy, which can be switched at runtime to generate appropriate email
 * messages for various types of customers.
 */
public class ContextEmail {
  private EmailStrategy strategy;

  /**
     * Constructs a ContextEmail with a specific email generation strategy.
     *
     * @param strategy The EmailStrategy to be used for generating email messages.
     */
  public ContextEmail(EmailStrategy strategy) {
    this.strategy = strategy;
  }

  /**
     * Sets a new email generation strategy at runtime.
     *
     * @param strategy The new EmailStrategy to be used for generating email messages.
     */
  public void setStrategy(EmailStrategy strategy) {
    this.strategy = strategy;
  }

  /**
     * Generates an email message using the current email strategy.
     *
     * @return A string representing the email message generated by the current strategy.
     */
  public String generateEmail() {
    return strategy.generateEmailMessage();
  }
}
